### PR TITLE
Fix the positioning of the close button in dismissable alerts

### PR DESCRIPTION
**Pull request by zoeesilcock**
screen shot 2015-09-23 at 15 47 27

### CODE REVIEW

**Comment by jorkas** [comment]
@zoeesilcock good if we try to include Screenshots/gifs on the PR:s!

**Comment by zoeesilcock** [comment]
Very true @jorkas, we forgot.

**Comment by jorkas** [comment]
LGTM!

**Comment by zoeesilcock** [comment]
Don't merge!

**Comment by zoeesilcock** [comment]
Ok fine, we'll put our fix on master.

**Pull request merged**
