### PR TITLE
Include panel in documentation around forms (Form heading)

### PR DESCRIPTION
**Pull request by jorkas**
screenshot 2015-06-24 11 57 53

### CODE REVIEW

**Comment by alexwoll** [comment]
Awesome!

**Comment by eliashedlund** [comment]
Looking good!
What about the button? Should it perhaps be inside the panel?

**Comment by jorkas** [comment]
@eliashedlund i don't have the answer on the button. The one with panel today doesn't have the button connected to the panel. Ideas? @mynewsdesk/design @mynewsdesk/frontend

**Comment by eliashedlund** [comment]
@jorkas Yeah I see what you mean. I wasn't sure either, maybe it's good as it is.

**Pull request merged**
